### PR TITLE
Feature/improve db interactions

### PR DESCRIPTION
**Pull request by fekete965**
# Related Issues

# Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

# Description
`DB` and `File System` interactions have been extracted.
Improved the way we connect to the DB and we added the ability to insert multiple records in one go into the DB.

## Fixes # (issue)
This PR will address the following issue: #10 

# Added to documentation?

- [x] README
- [x] Documentation

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by fekete965** [comment]
**Last 4 commits only!**

**Comment by fekete965** [comment]
@0xSooki issues have been resolved. :)

**Comment by 0xSooki** [comment]
Amazing, will check it tomorrow morning but it seems perfect, great job :)

**Review by 0xSooki — APPROVED** [review]
Clean code & amazing improvement to the db

**Comment by 0xSooki** [comment]
Just one quick thing, could you please change the target branch to develop?

**Comment by fekete965** [comment]
Ah my bad! I accidentally rebased to main. 🤦

**Comment by fekete965** [comment]
@0xSooki all done. Finally, a clean commit tree :)

**Comment by 0xSooki** [comment]
Amazing, thank you :)

**Review by 0xSooki — APPROVED** [review]

**Pull request merged**
