### PR TITLE
Feature/refactor codebase

### PR DESCRIPTION
**Pull request by fekete965**
PR for issue #3

### CODE REVIEW

**Comment by 0xSooki** [comment]
Amazing, thank you. Could you please change the target branch to develop instead of main?

**Comment by fekete965** [comment]
@0xSooki yes, of course. :)

**Comment by fekete965** [comment]
@0xSooki all done. 💪

**Comment by 0xSooki** [comment]
Would you mind solving conflicts regarding the mongodb update? As you did an amazing job with the repo so it would be much appreciated

**Comment by fekete965** [comment]
Yes, of course! I'll resolve any conflict :)

**Comment by 0xSooki** [comment]
Thank you, much appreciated :)

**Comment by fekete965** [comment]
@0xSooki I had some trouble to checkout to my branch after I have changed the origin of it to develop.
I did resolve the conflicts, but I was not able to test it myself locally.

I will create an "issue" where I would propose something regarding data saving to the DB and I will also be able to test my changes properly.

Sorry for the trouble!

**Comment by 0xSooki** [comment]
It's totally okay, take your time, you've already did an amazing job

**Comment by fekete965** [comment]
@0xSooki Conflict should be resolved.

**Review by 0xSooki — APPROVED** [review]
Amazing & clean refactor, awesome directory structure, caseing & much appreciated that you've added engine specification in package.json

**Pull request merged**
