### PR TITLE
Mongodb

### PR DESCRIPTION
**Pull request by cimok2000**
## Describe your changes
Implemented MongoDB into the codebase for saving NFTs to a Database.
This completes this issue: https://github.com/0xSooki/nft-rarity-generator/issues/4

### CODE REVIEW

**Comment by cimok2000** [comment]
I tested this on my own local environment and also on [MongoDBs Free Hosts ](https://cloud.mongodb.com/).

**Comment by 0xSooki** [comment]
Amazing, thank you. Could you please change the target branch to develop instead of main?

**Comment by cimok2000** [comment]
I have changed the base branch, sorry about that!

**Review by 0xSooki — APPROVED** [review]
Amazing implementation of MongoDB, much appreciated that you also updated the doumentation & added env variable example

**Pull request merged**
