### PR TITLE
Feature/improve cli menu

### PR DESCRIPTION
**Pull request by fekete965**
# Related Issues

# Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

# Description

# Added to documentation?

- [x] Documentation

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by fekete965** [comment]
@0xSooki this is a fairly big change to the application.
I will need to add another commit with the documentation change and a simple map regarding the menu.

**Comment by fekete965** [comment]
Super-liner is very bloody annoying and cannot seem to be using the most recent version of our linter...
I will transform classes back to functions.

**Comment by fekete965** [comment]
@0xSooki documentation has been updated.
PR is good for a review.

**Comment by 0xSooki** [comment]
Will check it soon

**Review by 0xSooki — APPROVED** [review]
Amazing work, I personally like how error messages are being stored & also the update on the README is much appreciated

**Pull request merged**
